---
default_language_version:
  python: "python3"
exclude: "^.*\b(migrations)\b.*$"
repos:
  - repo: "https://github.com/adamchainz/django-upgrade"
    rev: "1.24.0"
    hooks:
      - id: "django-upgrade"
        args: ['--target-version', '5.1']
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.11.8"
    hooks:
      - id: "ruff"
        args: ["--fix"]
      - id: "ruff-format"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v1.15.0'
    hooks:
      - id: "mypy"
        exclude: "src/.*/migrations/.*.py"
        additional_dependencies:
          - "django-stubs[compatible-mypy]"
          - "django-stubs-ext"
          - "types-requests"
          - "django-allauth==0.61.1"
          - "django-bootstrap5==23.4"
          - "django-cors-headers==4.3.1"
          - "django-oauth-toolkit==2.3.0"
          - "psycopg2-binary==2.9.9"
          - "django-filter==24.2"
          - "django-tables2==2.7.0"
          - "django-debug-toolbar==4.1.0"
...
