repos:
  - repo: "https://github.com/ambv/black"
    rev: "21.4b2"
    hooks:
    - id: "black"
      language_version: "python3.7"
  - repo: "https://gitlab.com/pycqa/flake8"
    rev: "3.9.1"
    hooks:
    - id: "flake8"
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: "v5.8.0"
    hooks:
    - id: "isort"
