cache: pip

language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r src/requirements/dev.txt

before_script:
  - psql -c "CREATE ROLE bornhack WITH LOGIN PASSWORD 'bornhack';"

script:
  - cp src/bornhack/environment_settings.py.dist.dev src/bornhack/environment_settings.py
  - cd src; python manage.py test
