name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    container: ubuntu:rolling

    strategy:
      matrix:
        #python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:10-2.5-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: bornhack
          POSTGRES_PASSWORD: bornhack
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libgdal-dev libpq-dev libffi7 libmagic1
      - name: Install python dependencies
        run: |
          python -m pip install -r src/requirements/dev.txt
      - name: Copy settings
        run: cp src/bornhack/environment_settings.py.dist.dev src/bornhack/environment_settings.py
      - name: Run tests
        run: coverage run --source src/ src/manage.py test src/
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      - name: Report to codecov
        run: codecov
        if: ${{ success() }}