name: Run tests for the BornHack website project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:10-2.5-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: bornhack
          POSTGRES_PASSWORD: bornhack

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements/dev.txt
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libgdal-dev libpq-dev
      - name: Copy settings
        run: cp src/bornhack/environment_settings.py.dist.dev src/bornhack/environment_settings.py
      - name: Run tests
        run: coverage run --source src/ src/manage.py test src/
        env:
          POSTGRES_HOST: postgres
      - name: Report to codecov
        run: codecov
        if: ${{ success() }}